/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UJIBOLEH;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class CEKTUBUH extends javax.swing.JFrame {

    /**
     * Creates new form CEKTUBUH
     */
    public CEKTUBUH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        Jantan = new javax.swing.JRadioButton();
        Betina = new javax.swing.JRadioButton();
        Proses = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();
        Saran = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 140, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 32, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 34, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 70, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 45, 14);
        getContentPane().add(Nama);
        Nama.setBounds(160, 60, 190, 30);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(160, 90, 120, 30);
        getContentPane().add(Berat);
        Berat.setBounds(160, 120, 120, 30);

        Jantan.setText("Laki");
        getContentPane().add(Jantan);
        Jantan.setBounds(160, 160, 43, 23);

        Betina.setText("Wanita");
        getContentPane().add(Betina);
        Betina.setBounds(160, 190, 70, 23);

        Proses.setText("Hitung");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(60, 230, 90, 23);

        jButton2.setText("Coba Lagi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 230, 110, 23);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(270, 230, 51, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 51));
        jLabel6.setText("Berad Badan ideal Anda");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 300, 133, 14);

        Ideal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdealActionPerformed(evt);
            }
        });
        getContentPane().add(Ideal);
        Ideal.setBounds(190, 290, 70, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 300, 20, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("cm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 100, 17, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(290, 140, 14, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 350, 150, 14);
        getContentPane().add(Hasil);
        Hasil.setBounds(10, 380, 380, 30);
        getContentPane().add(Saran);
        Saran.setBounds(10, 420, 380, 30);

        jPanel1.setBackground(new java.awt.Color(207, 192, 192));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(255, 102, 153));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        try {
        int ti = Integer.valueOf(Tinggi.getText());
        int bt = Integer.valueOf(Berat.getText());
        int h1 = 0;
        if (Jantan.isSelected()) {
            h1 = (ti - 100) * 1;
        } else if (Betina.isSelected()) {
            h1 = (ti - 104) * 1;
        }
        String Ideal = Integer.toString(h1);

        if (h1 < bt) {
            Hasil.setText(Ideal);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya Anda Overweight :D ");
            Saran.setText("Banyaklah Mengerjakan PR Matematika sampai lupa waktu");
        } else if (h1 > bt) {
            Hasil.setText(Ideal);
            Hasil.setText("Maaf " + Nama.getText() + ", Sepertinya Anda Underweight :D ");
            Saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        } else {
            Hasil.setText(Ideal);
            Hasil.setText("GOTCHA!! " + Nama.getText() + ", Berat Badan Anda Ideal :( ");
            Saran.setText("Lanjutkan dan terapkan pola hidup santuy :D");
        }

        }catch (Exception e) {
            JOptionPane.showConfirmDialog(null,"Ya Alloh Ughtea ga teliti :D");
        }
    }//GEN-LAST:event_ProsesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  Tinggi.setText("");
Berat.setText("");
Saran.setText("");
Hasil.setText("");
Ideal.setText("");
Nama.setText("");
buttonGroup1.clearSelection();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void IdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdealActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CEKTUBUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CEKTUBUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CEKTUBUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CEKTUBUH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CEKTUBUH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JRadioButton Betina;
    private javax.swing.JTextField Hasil;
    private javax.swing.JTextField Ideal;
    private javax.swing.JRadioButton Jantan;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton Proses;
    private javax.swing.JTextField Saran;
    private javax.swing.JTextField Tinggi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
