/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LATIHAN1;

/**
 *
 * @author Asus
 */
public class Biodata extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Biodata() {
        initComponents();

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Kelas = new javax.swing.JComboBox<>();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        btnOke = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(167, 11, 70, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 50, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 50, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 150, 40, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 190, 50, 15);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 50, 15);
        getContentPane().add(Nama);
        Nama.setBounds(120, 60, 170, 30);
        getContentPane().add(Absen);
        Absen.setBounds(120, 100, 170, 30);
        getContentPane().add(Alamat);
        Alamat.setBounds(120, 220, 170, 30);

        Kelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XRPL 1", "XRPL 2", "XRPL 3", "XRPL 4", "XRPL 5", "XRPL 6", "XRPL 7", "XTKJ 1 ", "XTKJ 2", "XTKJ 3", "XTKJ 4", "XTKJ 5", "XTKJ 6" }));
        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        getContentPane().add(Kelas);
        Kelas.setBounds(120, 150, 170, 21);

        Jurusan.add(rdb1);
        rdb1.setText("RPL");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb1);
        rdb1.setBounds(120, 190, 100, 23);

        Jurusan.add(rdb2);
        rdb2.setText("TKJ");
        getContentPane().add(rdb2);
        rdb2.setBounds(220, 190, 110, 23);

        btnOke.setText("SEND");
        btnOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeActionPerformed(evt);
            }
        });
        getContentPane().add(btnOke);
        btnOke.setBounds(110, 280, 59, 23);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(210, 280, 55, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\Telkom png.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 0, 420, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String kelas = Kelas.getSelectedItem().toString();
        String jurusan = "";
        String alamat = Alamat.getText();
        
        if (rdb1.isSelected())
            jurusan = "RPL";
                    else if (rdb2.isSelected())
                        jurusan = "TKJ";
        else
        if (Kelas.getSelectedItem()== "XRPL 1"){  
        }
         if (Kelas.getSelectedItem()== "XRPL 2"){  
        }
          if (Kelas.getSelectedItem()== "XRPL 3"){  
        }
           if (Kelas.getSelectedItem()== "XRPL 4"){  
        }
            if (Kelas.getSelectedItem()== "XRPL 5"){  
        }
             if (Kelas.getSelectedItem()== "XRPL 6"){  
        }
              if (Kelas.getSelectedItem()== "XRPL 7"){  
        }
               if (Kelas.getSelectedItem()== "XTKJ 1"){  
        }
                if (Kelas.getSelectedItem()== "XTKJ 2"){  
        }
                 if (Kelas.getSelectedItem()== "XTKJ 3"){  
        }
                  if (Kelas.getSelectedItem()== "XTKJ 4"){  
        }
                   if (Kelas.getSelectedItem()== "XTKJ 5"){  
        }
                    if (Kelas.getSelectedItem()== "XTKJ 6"){  
        }   
                      new Frame2(nama, absen, kelas, jurusan, alamat).setVisible(true);
    }//GEN-LAST:event_btnOkeActionPerformed
       
    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biodata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biodata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.ButtonGroup Jurusan;
    private javax.swing.JComboBox<String> Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton btnOke;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
