/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LATIHAN1;

/**
 *
 * @author Asus
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2(String nama, String absen, String kelas, String jurusan, String alamat) {
        initComponents();
        Nama.setText(nama);
        Absen.setText(absen);
        Kelas.setText(kelas);
        Jurusan.setText(jurusan);
        Alamat.setText(alamat);
    }

    Frame2() {
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Kelas = new javax.swing.JLabel();
        Jurusan = new javax.swing.JLabel();
        Alamat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 20, 90, 22);

        Nama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nama.setText("Hasil1");
        getContentPane().add(Nama);
        Nama.setBounds(40, 80, 90, 15);

        Absen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Absen.setText("Hasil2");
        getContentPane().add(Absen);
        Absen.setBounds(40, 110, 90, 15);

        Kelas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Kelas.setText("Hasil3");
        getContentPane().add(Kelas);
        Kelas.setBounds(40, 140, 90, 15);

        Jurusan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jurusan.setText("Hasil4");
        getContentPane().add(Jurusan);
        Jurusan.setBounds(40, 170, 90, 15);

        Alamat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Alamat.setText("Hasi5l");
        getContentPane().add(Alamat);
        Alamat.setBounds(40, 200, 90, 15);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\indosad.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 100, 400, 300);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Documents\\Telkom png.png")); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, -40, 410, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JLabel Alamat;
    private javax.swing.JLabel Jurusan;
    private javax.swing.JLabel Kelas;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
