name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

- name: Setup Dotnet for use with actions
  uses: actions/setup-dotnet@v1.0.0
  with:
    # Version to use. E.g. 2.2.104
    version: # optional
